### ISSUE TITLE
移動手段の追加

### ISSUE THREAD

**Issue by turu18** [mirumirumi/zenn#2]
移動手段にpublic_transportを追加することは可能でしょうか。

**Comment by mirumirumi** [comment]
まずはじめに、このリポジトリは僕が Zenn に投稿している記事全体の管理用のものです。
どの記事についての話題か明記していただいたほうがお互いにとってよいですし、おそらく機能追加リクエスト的なことをおっしゃっていると思うのでなおさら各リポジトリへの issue 投稿をしたほうがよろしいかと思います。

おそらく [how-far-can-i-go](https://github.com/mirumirumi/how-far-can-i-go) の話題だと思いますのでここで答えてしまいますが、非常に高額な API を使っているというのもあり、今後大幅な機能追加をする予定はないというのが背景にあります。

それに加え、公共交通機関（public_transport ってそういう意味合いであってますよね？）は日本に関するデータが不足していて、たしか利用範囲外だったような気がします。

いずれにせよご希望に添えない形となります。よろしくお願いします。
